function Questions() {
  const questionList = [
    [
      "What is a mimic?",
      "A non-speaking pantomimer.",
      "Someone that imitates you.",
      "A carnivorous chest.",
      "A miniature microphone.",
      "3",
      "5",
      "An interesting one.  This is not only from the Dungeons & Dragons game I loved playing as a teen but could also be used to descibe me.  I look like a person but tend to act ... well ... differently and am therefore often misunderstood.  So, I've become good at playing a part, usually a wallflower.",
    ],
    [
      "What is the name of the villian in the Dungeons & Dragons cartoon series?",
      "Voldamort",
      "Vladamir",
      "Vermathax",
      "Venger",
      "4",
      "10",
      "Growing up, this was one of the best cartoons of its time.  Kids getting pulled into an alternate dimension where they got to play their D&D characters.  Just one of many things I wish was possible in reality because at least there, I would have fit in better than here. And best of all, there was little Uni running around.",
    ],
    [
      "What is the full name of the SDF-1?",
      "Super Deformed Figure-1",
      "Super Dimensional Fortress-1",
      "Silver Dueling Falcion-1",
      "Sonic Dinner Fork-1",
      "2",
      "10",
      "Robotech.  The tv series that got me started in my love of anime.  A unique series at the time in that it told a complete story and wasn't afraid to show the death of a loved character.  ",
    ],
    [
      "Who is the King of the Monsters?",
      "Simba the lion.",
      "A king cobra.",
      "A black widow spider.",
      "Godzilla.",
      "4",
      "5",
      "story",
    ],
    [
      "What are the names of the main characters in Genshin Impact?",
      "Aether and Lumine",
      "Simba and Scar",
      "Rocky and Bullwinkle",
      "Rick and Morty",
      "1",
      "15",
      "story",
    ],
    [
      "What name is given to the character shown in the game background?",
      "The Lady Amalethia",
      "Princess Cadmine",
      "Queen Malevalent",
      "Princess Peach",
      "1",
      "5",
      "story",
    ],
    [
      "How many Fred Saberhagen Swords of Power are there?",
      "One.",
      "Three",
      "Seven",
      "Twelve.",
      "4",
      "5",
      "story",
    ],
    [
      "In the Piers Anthony comedy series, what state does Xanth overlap?",
      "California",
      "Florida",
      "Alaska",
      "Hawaii",
      "2",
      "5",
      "story",
    ],
    [
      "Which of the following is NOT a type of Transformer?",
      "Autobots",
      "Predacons",
      "Dinobots",
      "Gobots",
      "4",
      "5",
      "story",
    ],
    [
      "An alicorn is _________.",
      "the horn of a unicorn.",
      "a winged unicorn.",
      "a type of corn.",
      "a medical problem with a foot.",
      "1",
      "5",
      "story",
    ],
    [
      "In what movie is the Death Blossom attack used?",
      "Pokemon",
      "Star Wars",
      "The Last Starfighter",
      "Dragonball",
      "3",
      "5",
      "story",
    ],
    [
      "Who played the character Jack in Legend?",
      "Bill Murry",
      "Steven Seagal",
      "Tom Cruise",
      "Bruce Willis",
      "3",
      "5",
      "story",
    ],
    [
      "In what sci-fi tv series did an alliance of races fight The Shadows?",
      "Star Trek",
      "Buck Rogers",
      "Battlestar Galactica",
      "Babylon 5",
      "4",
      "5",
      "story",
    ],
    [
      "What anime series featured a Moon Pricess?",
      "Sailor Moon",
      "Moon Over Miami.",
      "My Little Pony",
      "Strawberry Shortcake",
      "1",
      "5",
      "story",
    ],
    [
      "Which of the following are not Blizzard games?",
      "Starcraft",
      "Minecraft",
      "Warcraft",
      "Diablo",
      "2",
      "5",
      "story",
    ],
    [
      "Which of the following is not science?",
      "Astrology",
      "Chemistry",
      "Biology",
      "Physics",
      "1",
      "5",
      "story",
    ],
    [
      "Ludo, the lovable, loyal monster is in what movie?",
      "Shrek",
      "Home",
      "Ghostbusters",
      "Labyrinth",
      "4",
      "5",
      "story",
    ],
    [
      "What are the mecha in Endless Waltz known as?",
      "Priest",
      "Gundams",
      "Cyborgs",
      "Gadgets",
      "2",
      "5",
      "story",
    ],
    [
      "What drawing style is used to design buildings?",
      "Line drawing",
      "Caricature",
      "Geometry",
      "Architecture",
      "4",
      "5",
      "story",
    ],
    [
      "What is the name of unicorns the firstborn?",
      "Assallum",
      "Amaltheia",
      "Arboron",
      "Andrameda",
      "1",
      "5",
      "story",
    ],
  ];

  return (
    <>
      <div className="visible">
        <div>{questionList[0][0]}</div>
        <div>{questionList[0][1]}</div>
        <div>{questionList[0][2]}</div>
        <div>{questionList[0][3]}</div>
        <div>{questionList[0][4]}</div>
        <div>{questionList[0][7]}</div>
        <div>Previous</div>
        <div>Next</div>
      </div>
    </>
  );
}

export default Questions;
